services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_routing_app_dev
    image: react_routing_app:01_dev
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/react_app
      - /react_app/node_modules

